### ISSUE TITLE
add Semiring Disj instance

### ISSUE THREAD

**Issue by jonsterling** [purescript/purescript-monoid#20]
PR incoming

**Comment by jonsterling** [comment]
I'm actually not sure that this is a great idea, since `Disj` is meant to focus on one aspect of a potential semiring. I may implement what I need in another way...

**Comment by garyb** [comment]
If you do do it we have a `purescript-semiring`s too, so it may be more appropriate there - I think it depends on `monoids` - https://github.com/purescript/purescript-semirings.

**Comment by garyb** [comment]
Oh, nevermind, that would be an orphan then, of course.
