### ISSUE TITLE
Rename mempty

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript-monoid#26]
Sounds un-PureScript-y. @garyb suggested leaving `Plus` as is and picking something here when modules get renamed.

**Comment by garyb** [comment]
`neutral` is the best I have so far, and I don't really like that.

**Comment by paf31** [comment]
`unit`? Although I'm also fine with `mempty`.

**Comment by garyb** [comment]
`unit` would conflict even more than `empty` would (since it's the value for `Unit`: unless we only provide it via monoid) :smile:

**Comment by texastoland** [comment]
My motivation in asking is because it's inconsistent with `fmap` etc.

**Comment by garyb** [comment]
Yeah, and it's `append`, not `mappend`. Although `append` is in `Semigroup` so it especially wouldn't make sense as `mappend`!

**Comment by rightfold** [comment]
`appendId`

**Comment by hdgarrood** [comment]
I think the fact that this has stayed open for as long as it has suggests that we should probably close it. Thoughts?

**Comment by paf31** [comment]
Agreed
