### ISSUE TITLE
Transformation Monoid

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-monoid#33]
Is it worth including something like `newtype Transformation = Transformation (t -> t)` with a `Monoid` over composition and `mempty = id`?

**Comment by garyb** [comment]
See `Endo`: https://github.com/purescript/purescript-monoid/blob/master/src/Data/Monoid/Endo.purs :smile:

**Comment by matthewleon** [comment]
Oh dear. Time to seriously up my (nonexistent) category theory game. Thanks.

**Comment by garyb** [comment]
If you're looking for the type you're half way there!
