### ISSUE TITLE
stack-safe Endo

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-monoid#41]
This would make it safe to `foldMap` into an `Endo`functor. @natefaubion I recall you making something like this on Slack at some point.

**Comment by natefaubion** [comment]
You can use an efficient Free Monoid representation. I used an Array for demo purposes, but you can also use CatList, which is what purescript-free uses.

**Comment by matthewleon** [comment]
Sadly, using `CatList` here would create a dependency loop. It does seem like the right datatype, though. Perhaps the best approach is to create a separate lib for this :/
