### ISSUE TITLE
mconcat?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-monoid#5]
Do you think this library should include a function `mconcat :: Monoid a => [a] -> a`, like Haskell's? I'd be happy to put a pull request together if so.

**Comment by wereHamster** [comment]
The function is called `fold`, here a stable link to the source: https://github.com/purescript/purescript-foldable-traversable/blob/363af1ede2e9b3a2ef956adb8ea5176ac24c0c79/src/Data/Foldable.purs#L171-L173
